sudo: required
services:
  - docker

before_install:
  - docker build -t marius/docker-react -f Dockerfile.dev .

script:
  - docker run marius/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
